# Generated by Django 6.0.3 on 2026-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=3000),
        ),
    ]
